[package]
name = "danktronics_bot"
version = "0.1.0"
authors = ["Sei4or <sei4or@gmail.com>"]
edition = "2018"

[dependencies]
serenity = { version = "0.8", features = ["client", "standard_framework", "voice", "rustls_backend", "cache"] }
anyhow = "1.0"
percent-encoding = "2.1.0"
